version: '3'
services:
  follower:
    build:
      context: ./
      dockerfile: follower.dockerfile
    environment:
      RBC_PORT: 8000
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  leader:
    build:
      context: ./
      dockerfile: leader.dockerfile
    environment:
      RBC_PORT: 8000
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

networks:
  demo_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
